# Generated by Django 4.2.11 on 2024-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField()),
                ('entry_id', models.IntegerField()),
                ('runtime', models.FloatField()),
                ('dataset', models.TextField()),
                ('model', models.TextField()),
                ('input_json', models.TextField()),
                ('stack_precision', models.FloatField()),
                ('stack_accuracy', models.FloatField()),
                ('stack_f1', models.FloatField()),
                ('stack_recall', models.FloatField()),
                ('output_json', models.TextField()),
            ],
        ),
    ]
